"""
Code generation configuration for steam_api.json -> Panda3D wrappers.

ALL interfaces in steam_api.json are generated by default.  Use the
settings below to adjust type mappings, skip specific interfaces or
methods, and provide per-interface overrides.

After modifying this file, re-run the code generator:
    ppython scripts/codegen.py

Or just build normally (codegen runs automatically before CMake):
    ppython setup.py build
"""

# ---------------------------------------------------------------------------
# Paths (relative to repository root)
# ---------------------------------------------------------------------------

# Location of the Steamworks API JSON definition
STEAM_API_JSON = "thirdparty/steamworks/public/steam/steam_api.json"

# Output directory for generated .h and .cpp files
OUTPUT_DIR = "source"

# ---------------------------------------------------------------------------
# Default char buffer size for methods that output strings via char* params.
# Individual methods can override this in INTERFACE_OVERRIDES below.
# ---------------------------------------------------------------------------

DEFAULT_BUFFER_SIZE = 1024

# ---------------------------------------------------------------------------
# The interface that gets the static init() / shutdown() lifecycle methods
# (SteamAPI_Init / SteamAPI_Shutdown).  Only ONE interface should have this.
# ---------------------------------------------------------------------------

LIFECYCLE_INTERFACE = "ISteamApps"

# ---------------------------------------------------------------------------
# Interfaces to skip entirely.
#
# These will NOT have wrapper code generated.  Use this for interfaces
# that are callback-only, server-only, or otherwise not relevant.
# ---------------------------------------------------------------------------

SKIP_INTERFACES = set()

# ---------------------------------------------------------------------------
# Return type map
#
# Steam type -> (C++ wrapper type, default return value, special_handling)
#
# special_handling values:
#   None      - direct return, no transformation
#   "string"  - const char* from Steam -> std::string, with null check
#   "steamid" - CSteamID -> .ConvertToUint64()
#
# A value of None (the whole entry) means "skip methods with this return type".
# ---------------------------------------------------------------------------

RETURN_TYPES = {
    "void":           ("void",               None,             None),
    "bool":           ("bool",               "false",          None),
    "int":            ("int",                "0",              None),
    "int32":          ("int",                "0",              None),
    "uint32":         ("unsigned int",       "0",              None),
    "int64":          ("long long",          "0",              None),
    "uint64":         ("unsigned long long", "0",              None),
    "uint16":         ("unsigned short",     "0",              None),
    "uint8":          ("unsigned char",      "0",              None),
    "float":          ("float",              "0.0f",           None),
    "double":         ("double",             "0.0",            None),
    "const char *":   ("std::string",        "std::string()",  "string"),
    "CSteamID":       ("unsigned long long", "0",              "steamid"),
    "AppId_t":        ("unsigned int",       "0",              None),
    "DepotId_t":      ("unsigned int",       "0",              None),
    "HAuthTicket":    ("unsigned int",       "0",              None),
    "RTime32":        ("unsigned int",       "0",              None),
    "AccountID_t":    ("unsigned int",       "0",              None),
    "SteamAPICall_t": None,  # Handled specially by ASYNC classification
}

# ---------------------------------------------------------------------------
# Parameter type map
#
# Steam type -> (C++ wrapper type, call_transform)
#
# call_transform values:
#   None    - pass argument directly
#   "c_str" - call .c_str() when forwarding to the Steam API
# ---------------------------------------------------------------------------

PARAM_TYPES = {
    "bool":           ("bool",                None),
    "int":            ("int",                 None),
    "int32":          ("int",                 None),
    "uint32":         ("unsigned int",        None),
    "int64":          ("long long",           None),
    "uint64":         ("unsigned long long",  None),
    "uint16":         ("unsigned short",      None),
    "uint8":          ("unsigned char",       None),
    "float":          ("float",               None),
    "double":         ("double",              None),
    "const char *":   ("const std::string &", "c_str"),
    "CSteamID":       ("unsigned long long",  "steamid_from"),
    "AppId_t":        ("unsigned int",        None),
    "DepotId_t":      ("unsigned int",        None),
    "HAuthTicket":    ("unsigned int",        None),
    "RTime32":        ("unsigned int",        None),
    "AccountID_t":    ("unsigned int",        None),
    "PublishedFileId_t": ("unsigned long long", None),
    "UGCHandle_t":    ("unsigned long long",  None),
    "SteamLeaderboard_t": ("unsigned long long", None),
    "SteamLeaderboardEntries_t": ("unsigned long long", None),
    "UGCQueryHandle_t": ("unsigned long long", None),
    "SteamInventoryResult_t": ("int",         None),
    "UGCUpdateHandle_t": ("unsigned long long", None),
    "ScreenshotHandle": ("unsigned int",      None),
    "SteamParamStringArray_t *": None,  # Skip - complex type
    "HHTMLBrowser":   ("unsigned int",        None),
    "PartyBeaconID_t": ("unsigned long long", None),
}

# ---------------------------------------------------------------------------
# Per-interface overrides  (optional)
#
# Any interface NOT listed here still gets generated with sensible defaults
# (class_name derived from interface name, no skipped methods, etc.).
#
# Available override keys:
#   class_name      (str)   - Override the wrapper class name
#   description     (str)   - Description for the class comment block
#   skip_methods    (list)  - Steam method names to omit from this interface
#   buffer_sizes    (dict)  - Per-method override: method_name -> buffer size
#   extra_includes  (list)  - Additional #include lines for the .cpp
# ---------------------------------------------------------------------------

INTERFACE_OVERRIDES = {
    "ISteamApps": {
        "description": (
            "Static wrapper around the Steamworks ISteamApps\n"
            "               interface, providing access to app ownership,\n"
            "               DLC, language, and installation information."
        ),
        "buffer_sizes": {
            "GetCurrentBetaName": 256,
        },
    },
    "ISteamRemoteStorage": {
        "extra_methods": [
            {
                "name": "file_write",
                "comment": "Write a string to a file in Steam Cloud.",
                "declaration": "bool file_write(const std::string &file, const std::string &data)",
                "implementation": [
                    "bool SteamRemoteStorage::file_write(const std::string &file, const std::string &data) {",
                    "  ISteamRemoteStorage *iface = SteamAPI_SteamRemoteStorage();",
                    "  if (!iface) return false;",
                    "  return iface->FileWrite(file.c_str(), data.c_str(), (int32)data.size());",
                    "}",
                ],
            },
            {
                "name": "file_read",
                "comment": "Read the contents of a Steam Cloud file as a string.",
                "declaration": "std::string file_read(const std::string &file)",
                "implementation": [
                    "std::string SteamRemoteStorage::file_read(const std::string &file) {",
                    "  ISteamRemoteStorage *iface = SteamAPI_SteamRemoteStorage();",
                    "  if (!iface) return std::string();",
                    "  int32 size = iface->GetFileSize(file.c_str());",
                    "  if (size <= 0) return std::string();",
                    "  std::string buf(size, '\\0');",
                    "  int32 read = iface->FileRead(file.c_str(), &buf[0], size);",
                    "  if (read <= 0) return std::string();",
                    "  buf.resize(read);",
                    "  return buf;",
                    "}",
                ],
            },
        ],
    },
    # Example: skip specific methods on an interface
    # "ISteamFriends": {
    #     "skip_methods": ["ActivateGameOverlayInviteDialogConnectString"],
    # },
}

# =========================================================================
# Async & Callback Configuration
# =========================================================================

# Enable async method generation (methods returning SteamAPICall_t).
# When True, async methods accept a Python callable (PyObject *callback)
# and invoke it with a dict when the CCallResult fires.
ENABLE_ASYNC_METHODS = True

# Enable broadcast (fire-and-forget) callback listeners.
# When True, the generator creates a CCallback handler per broadcast
# struct and fires Panda3D events via messenger.send().
# Users listen with self.accept("Steam-GameOverlayActivated", handler).
ENABLE_BROADCAST_CALLBACKS = True

# Prefix prepended to broadcast event names.
# With the default "Steam-", GameOverlayActivated_t fires as
# "Steam-GameOverlayActivated".  Set to "" for no prefix.
BROADCAST_EVENT_PREFIX = "Steam-"

# ---------------------------------------------------------------------------
# Callback structs to skip
#
# These will NOT have result data classes or handlers generated.
# Use this for callback structs with exotic fields or that you don't need.
# ---------------------------------------------------------------------------

SKIP_CALLBACK_STRUCTS = set()

# ---------------------------------------------------------------------------
# Broadcast callbacks
#
# These are "fire-and-forget" callbacks that Steam dispatches without a
# preceding API call.  They fire as Panda3D events via the messenger:
#
#   self.accept("Steam-GameOverlayActivated", self._on_overlay)
#
# The handler receives a single dict argument with the struct fields.
# ---------------------------------------------------------------------------

BROADCAST_CALLBACKS = [
    # User / authentication
    "SteamServersConnected_t",
    "SteamServersDisconnected_t",
    "SteamServerConnectFailure_t",
    "ValidateAuthTicketResponse_t",
    "GetAuthSessionTicketResponse_t",
    "MicroTxnAuthorizationResponse_t",
    "LicensesUpdated_t",

    # Friends
    "PersonaStateChange_t",
    "GameOverlayActivated_t",
    "GameLobbyJoinRequested_t",

    # Matchmaking
    "LobbyDataUpdate_t",
    "LobbyChatUpdate_t",
    "LobbyGameCreated_t",
    "LobbyInvite_t",

    # Apps
    "DlcInstalled_t",
    "NewUrlLaunchParameters_t",

    # User stats
    "UserStatsStored_t",
    "UserAchievementStored_t",

    # Screenshots
    "ScreenshotRequested_t",
    "ScreenshotReady_t",

    # UGC / Workshop
    "ItemInstalled_t",
]
