// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamRemotePlay
// Description : Wrapper around ISteamRemotePlay.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamRemotePlay {
PUBLISHED:
  static unsigned int get_session_count();
  static bool show_remote_play_together_ui();
  static bool send_remote_play_together_invite(unsigned long long steam_id_friend);
  static bool enable_remote_play_together_direct_input();
  static void disable_remote_play_together_direct_input();

private:
  SteamRemotePlay() = delete;
};
