// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamInput
// Description : Wrapper around ISteamInput.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamInput {
PUBLISHED:
  static bool init(bool explicitly_call_run_frame);
  static bool shutdown();
  static bool set_input_action_manifest_file_path(const std::string & input_action_manifest_absolute_path);
  static void run_frame(bool reserved_value);
  static bool wait_for_data(bool wait_forever, unsigned int timeout);
  static bool new_data_available();
  static void enable_device_callbacks();
  static std::string get_glyph_png_for_action_origin(int origin, int size, unsigned int flags);
  static std::string get_glyph_svg_for_action_origin(int origin, unsigned int flags);
  static std::string get_glyph_for_action_origin_legacy(int origin);
  static std::string get_string_for_action_origin(int origin);
  static std::string get_string_for_xbox_origin(int origin);
  static std::string get_glyph_for_xbox_origin(int origin);
  static int translate_action_origin(int destination_input_type, int source_origin);
  static unsigned short get_session_input_configuration_settings();

private:
  SteamInput() = delete;
};
