// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamHTMLSurface
// Description : Wrapper around ISteamHTMLSurface.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamHTMLSurface {
PUBLISHED:
  static bool init();
  static bool shutdown();
  static void set_cookie(const std::string & hostname, const std::string & key, const std::string & value, const std::string & path, unsigned int expires, bool secure, bool http_only);

private:
  SteamHTMLSurface() = delete;
};
