// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

// Provide a PyObject declaration that works for both
// interrogate (CPPPARSER) and normal C++ compilation.
#ifdef CPPPARSER
struct _object;
typedef _object PyObject;
#else
#include <Python.h>
#endif
