// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamFriends
// Description : Wrapper around ISteamFriends.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamFriends {
PUBLISHED:
  static std::string get_persona_name();
  static int get_persona_state();
  static int get_friend_count(int friend_flags);
  static unsigned long long get_friend_by_index(int friend_val, int friend_flags);
  static int get_friend_relationship(unsigned long long steam_id_friend);
  static int get_friend_persona_state(unsigned long long steam_id_friend);
  static std::string get_friend_persona_name(unsigned long long steam_id_friend);
  static std::string get_friend_persona_name_history(unsigned long long steam_id_friend, int persona_name);
  static int get_friend_steam_level(unsigned long long steam_id_friend);
  static std::string get_player_nickname(unsigned long long steam_id_player);
  static int get_friends_group_count();
  static bool has_friend(unsigned long long steam_id_friend, int friend_flags);
  static int get_clan_count();
  static unsigned long long get_clan_by_index(int clan);
  static std::string get_clan_name(unsigned long long steam_id_clan);
  static std::string get_clan_tag(unsigned long long steam_id_clan);
  static int get_friend_count_from_source(unsigned long long steam_id_source);
  static unsigned long long get_friend_from_source_by_index(unsigned long long steam_id_source, int friend_val);
  static bool is_user_in_source(unsigned long long steam_id_user, unsigned long long steam_id_source);
  static void set_in_game_voice_speaking(unsigned long long steam_id_user, bool speaking);
  static void activate_game_overlay(const std::string & dialog);
  static void activate_game_overlay_to_user(const std::string & dialog, unsigned long long steam_id);
  static void activate_game_overlay_to_web_page(const std::string & url, int mode);
  static void activate_game_overlay_to_store(unsigned int app_id, int flag);
  static void set_played_with(unsigned long long steam_id_user_played_with);
  static void activate_game_overlay_invite_dialog(unsigned long long steam_id_lobby);
  static int get_small_friend_avatar(unsigned long long steam_id_friend);
  static int get_medium_friend_avatar(unsigned long long steam_id_friend);
  static int get_large_friend_avatar(unsigned long long steam_id_friend);
  static bool request_user_information(unsigned long long steam_id_user, bool require_name_only);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_clan_officer_list(unsigned long long steam_id_clan, PyObject *callback);
  static unsigned long long get_clan_owner(unsigned long long steam_id_clan);
  static int get_clan_officer_count(unsigned long long steam_id_clan);
  static unsigned long long get_clan_officer_by_index(unsigned long long steam_id_clan, int officer);
  static bool set_rich_presence(const std::string & key, const std::string & value);
  static void clear_rich_presence();
  static std::string get_friend_rich_presence(unsigned long long steam_id_friend, const std::string & key);
  static int get_friend_rich_presence_key_count(unsigned long long steam_id_friend);
  static std::string get_friend_rich_presence_key_by_index(unsigned long long steam_id_friend, int key);
  static void request_friend_rich_presence(unsigned long long steam_id_friend);
  static bool invite_user_to_game(unsigned long long steam_id_friend, const std::string & connect_string);
  static int get_coplay_friend_count();
  static unsigned long long get_coplay_friend(int coplay_friend);
  static int get_friend_coplay_time(unsigned long long steam_id_friend);
  static unsigned int get_friend_coplay_game(unsigned long long steam_id_friend);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long join_clan_chat_room(unsigned long long steam_id_clan, PyObject *callback);
  static bool leave_clan_chat_room(unsigned long long steam_id_clan);
  static int get_clan_chat_member_count(unsigned long long steam_id_clan);
  static unsigned long long get_chat_member_by_index(unsigned long long steam_id_clan, int user);
  static bool send_clan_chat_message(unsigned long long steam_id_clan_chat, const std::string & text);
  static bool is_clan_chat_admin(unsigned long long steam_id_clan_chat, unsigned long long steam_id_user);
  static bool is_clan_chat_window_open_in_steam(unsigned long long steam_id_clan_chat);
  static bool open_clan_chat_window_in_steam(unsigned long long steam_id_clan_chat);
  static bool close_clan_chat_window_in_steam(unsigned long long steam_id_clan_chat);
  static bool set_listen_for_friends_messages(bool intercept_enabled);
  static bool reply_to_friend_message(unsigned long long steam_id_friend, const std::string & msg_to_send);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_follower_count(unsigned long long steam_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long is_following(unsigned long long steam_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long enumerate_following_list(unsigned int start_index, PyObject *callback);
  static bool is_clan_public(unsigned long long steam_id_clan);
  static bool is_clan_official_game_group(unsigned long long steam_id_clan);
  static int get_num_chats_with_unread_priority_messages();
  static void activate_game_overlay_remote_play_together_invite_dialog(unsigned long long steam_id_lobby);
  static bool register_protocol_in_overlay_browser(const std::string & protocol);
  static void activate_game_overlay_invite_dialog_connect_string(const std::string & connect_string);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_equipped_profile_items(unsigned long long steam_id, PyObject *callback);
  static bool has_equipped_profile_item(unsigned long long steam_id, int item_type);
  static std::string get_profile_item_property_string(unsigned long long steam_id, int item_type, int prop);
  static unsigned int get_profile_item_property_uint(unsigned long long steam_id, int item_type, int prop);

private:
  SteamFriends() = delete;
};
