// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamScreenshots
// Description : Wrapper around ISteamScreenshots.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamScreenshots {
PUBLISHED:
  static void trigger_screenshot();
  static void hook_screenshots(bool hook);
  static bool is_screenshots_hooked();

private:
  SteamScreenshots() = delete;
};
