// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamController.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamController interface pointer, or nullptr if not initialized.
static ISteamController *_get_steam_controller() {
  return SteamAPI_SteamController();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::init
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamController::init() {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return false;
  return iface->Init();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::shutdown
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamController::shutdown() {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return false;
  return iface->Shutdown();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::run_frame
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamController::run_frame() {
  ISteamController *iface = _get_steam_controller();
  if (iface) iface->RunFrame();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::get_glyph_for_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamController::get_glyph_for_action_origin(int origin) {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return std::string();
  const char *result = iface->GetGlyphForActionOrigin(static_cast<EControllerActionOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::get_string_for_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamController::get_string_for_action_origin(int origin) {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return std::string();
  const char *result = iface->GetStringForActionOrigin(static_cast<EControllerActionOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::get_string_for_xbox_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamController::get_string_for_xbox_origin(int origin) {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return std::string();
  const char *result = iface->GetStringForXboxOrigin(static_cast<EXboxOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::get_glyph_for_xbox_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamController::get_glyph_for_xbox_origin(int origin) {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return std::string();
  const char *result = iface->GetGlyphForXboxOrigin(static_cast<EXboxOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamController::translate_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamController::translate_action_origin(int destination_input_type, int source_origin) {
  ISteamController *iface = _get_steam_controller();
  if (!iface) return 0;
  return iface->TranslateActionOrigin(static_cast<ESteamInputType>(destination_input_type), static_cast<EControllerActionOrigin>(source_origin));
}

#endif  // CPPPARSER
