// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamInventory
// Description : Wrapper around ISteamInventory.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamInventory {
PUBLISHED:
  static int get_result_status(int result_handle);
  static unsigned int get_result_timestamp(int result_handle);
  static void destroy_result(int result_handle);
  static void send_item_drop_heartbeat();
  static bool load_item_definitions();
  static unsigned int get_num_items_with_prices();

private:
  SteamInventory() = delete;
};
