// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamTimeline
// Description : Wrapper around ISteamTimeline.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamTimeline {
PUBLISHED:
  static void set_timeline_tooltip(const std::string & description, float time_delta);
  static void clear_timeline_tooltip(float time_delta);
  static void set_timeline_game_mode(int mode);
  static void start_game_phase();
  static void end_game_phase();
  static void set_game_phase_id(const std::string & phase_id);
  static void add_game_phase_tag(const std::string & tag_name, const std::string & tag_icon, const std::string & tag_group, unsigned int priority);
  static void set_game_phase_attribute(const std::string & attribute_group, const std::string & attribute_value, unsigned int priority);
  static void open_overlay_to_game_phase(const std::string & phase_id);

private:
  SteamTimeline() = delete;
};
