// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamFriends.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamFriends interface pointer, or nullptr if not initialized.
static ISteamFriends *_get_steam_friends() {
  return SteamAPI_SteamFriends();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_persona_name
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamFriends::get_persona_name() {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return std::string();
  const char *result = iface->GetPersonaName();
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_persona_state
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamFriends::get_persona_state() {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetPersonaState();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_friend_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamFriends::get_friend_count(int friend_flags) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetFriendCount(friend_flags);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_friend_by_index
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamFriends::get_friend_by_index(int friend_val, int friend_flags) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetFriendByIndex(friend_val, friend_flags).ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_friends_group_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamFriends::get_friends_group_count() {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetFriendsGroupCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_clan_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamFriends::get_clan_count() {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetClanCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_clan_by_index
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamFriends::get_clan_by_index(int clan) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetClanByIndex(clan).ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::activate_game_overlay
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamFriends::activate_game_overlay(const std::string & dialog) {
  ISteamFriends *iface = _get_steam_friends();
  if (iface) iface->ActivateGameOverlay(dialog.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::activate_game_overlay_to_web_page
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamFriends::activate_game_overlay_to_web_page(const std::string & url, int mode) {
  ISteamFriends *iface = _get_steam_friends();
  if (iface) iface->ActivateGameOverlayToWebPage(url.c_str(), static_cast<EActivateGameOverlayToWebPageMode>(mode));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::activate_game_overlay_to_store
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamFriends::activate_game_overlay_to_store(unsigned int app_id, int flag) {
  ISteamFriends *iface = _get_steam_friends();
  if (iface) iface->ActivateGameOverlayToStore(app_id, static_cast<EOverlayToStoreFlag>(flag));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::set_rich_presence
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamFriends::set_rich_presence(const std::string & key, const std::string & value) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return false;
  return iface->SetRichPresence(key.c_str(), value.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::clear_rich_presence
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamFriends::clear_rich_presence() {
  ISteamFriends *iface = _get_steam_friends();
  if (iface) iface->ClearRichPresence();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_coplay_friend_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamFriends::get_coplay_friend_count() {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetCoplayFriendCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_coplay_friend
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamFriends::get_coplay_friend(int coplay_friend) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetCoplayFriend(coplay_friend).ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::set_listen_for_friends_messages
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamFriends::set_listen_for_friends_messages(bool intercept_enabled) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return false;
  return iface->SetListenForFriendsMessages(intercept_enabled);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::get_num_chats_with_unread_priority_messages
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamFriends::get_num_chats_with_unread_priority_messages() {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return 0;
  return iface->GetNumChatsWithUnreadPriorityMessages();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::register_protocol_in_overlay_browser
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamFriends::register_protocol_in_overlay_browser(const std::string & protocol) {
  ISteamFriends *iface = _get_steam_friends();
  if (!iface) return false;
  return iface->RegisterProtocolInOverlayBrowser(protocol.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamFriends::activate_game_overlay_invite_dialog_connect_string
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamFriends::activate_game_overlay_invite_dialog_connect_string(const std::string & connect_string) {
  ISteamFriends *iface = _get_steam_friends();
  if (iface) iface->ActivateGameOverlayInviteDialogConnectString(connect_string.c_str());
}

#endif  // CPPPARSER
