// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamApps.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamApps interface pointer, or nullptr if not initialized.
static ISteamApps *_get_steam_apps() {
  return SteamAPI_SteamApps();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::init
//       Access: Published, Static
//  Description: Initializes the Steamworks API.
////////////////////////////////////////////////////////////////////
bool SteamApps::init() {
  return SteamAPI_Init();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::shutdown
//       Access: Published, Static
//  Description: Shuts down the Steamworks API.
////////////////////////////////////////////////////////////////////
void SteamApps::shutdown() {
  SteamAPI_Shutdown();
}

// Forward declarations for async call-result registration
extern void _steam_async_call_FileDetailsResult_t(SteamAPICall_t, PyObject *);

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_subscribed
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_subscribed() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsSubscribed();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_low_violence
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_low_violence() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsLowViolence();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_cybercafe
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_cybercafe() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsCybercafe();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_vac_banned
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_vac_banned() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsVACBanned();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_current_game_language
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamApps::get_current_game_language() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return std::string();
  const char *result = iface->GetCurrentGameLanguage();
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_available_game_languages
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamApps::get_available_game_languages() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return std::string();
  const char *result = iface->GetAvailableGameLanguages();
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_subscribed_app
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_subscribed_app(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsSubscribedApp(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_dlc_installed
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_dlc_installed(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsDlcInstalled(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_earliest_purchase_unix_time
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamApps::get_earliest_purchase_unix_time(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return 0;
  return iface->GetEarliestPurchaseUnixTime(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_subscribed_from_free_weekend
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_subscribed_from_free_weekend() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsSubscribedFromFreeWeekend();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_dlc_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamApps::get_dlc_count() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return 0;
  return iface->GetDLCCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::install_dlc
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamApps::install_dlc(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (iface) iface->InstallDLC(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::uninstall_dlc
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamApps::uninstall_dlc(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (iface) iface->UninstallDLC(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::request_app_proof_of_purchase_key
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamApps::request_app_proof_of_purchase_key(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (iface) iface->RequestAppProofOfPurchaseKey(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_current_beta_name
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamApps::get_current_beta_name() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return std::string();
  char buf[256];
  bool ok = iface->GetCurrentBetaName(buf, sizeof(buf));
  if (ok) return std::string(buf);
  return std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::mark_content_corrupt
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::mark_content_corrupt(bool missing_files_only) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->MarkContentCorrupt(missing_files_only);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_app_install_dir
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamApps::get_app_install_dir(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return std::string();
  char buf[1024];
  uint32 len = iface->GetAppInstallDir(app_id, buf, sizeof(buf));
  if (len > 0) return std::string(buf);
  return std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_app_installed
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_app_installed(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsAppInstalled(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_app_owner
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamApps::get_app_owner() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return 0;
  return iface->GetAppOwner().ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_launch_query_param
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamApps::get_launch_query_param(const std::string & key) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return std::string();
  const char *result = iface->GetLaunchQueryParam(key.c_str());
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_app_build_id
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamApps::get_app_build_id() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return 0;
  return iface->GetAppBuildId();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::request_all_proof_of_purchase_keys
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamApps::request_all_proof_of_purchase_keys() {
  ISteamApps *iface = _get_steam_apps();
  if (iface) iface->RequestAllProofOfPurchaseKeys();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_file_details
//       Access: Published, Static
//  Description: Async. Invokes callback(dict) on completion.
////////////////////////////////////////////////////////////////////
unsigned long long SteamApps::get_file_details(const std::string & file_name, PyObject *callback) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return 0;
  SteamAPICall_t call = iface->GetFileDetails(file_name.c_str());
  if (call == k_uAPICallInvalid) return 0;
  if (callback && callback != Py_None && PyCallable_Check(callback)) {
    _steam_async_call_FileDetailsResult_t(call, callback);
  }
  return (unsigned long long)call;
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::get_launch_command_line
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamApps::get_launch_command_line() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return std::string();
  char buf[1024];
  int len = iface->GetLaunchCommandLine(buf, sizeof(buf));
  if (len > 0) return std::string(buf);
  return std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::is_subscribed_from_family_sharing
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::is_subscribed_from_family_sharing() {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->BIsSubscribedFromFamilySharing();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::set_dlc_context
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::set_dlc_context(unsigned int app_id) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->SetDlcContext(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamApps::set_active_beta
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamApps::set_active_beta(const std::string & beta_name) {
  ISteamApps *iface = _get_steam_apps();
  if (!iface) return false;
  return iface->SetActiveBeta(beta_name.c_str());
}

#endif  // CPPPARSER
