// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamScreenshots.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamScreenshots interface pointer, or nullptr if not initialized.
static ISteamScreenshots *_get_steam_screenshots() {
  return SteamAPI_SteamScreenshots();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamScreenshots::trigger_screenshot
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamScreenshots::trigger_screenshot() {
  ISteamScreenshots *iface = _get_steam_screenshots();
  if (iface) iface->TriggerScreenshot();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamScreenshots::hook_screenshots
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamScreenshots::hook_screenshots(bool hook) {
  ISteamScreenshots *iface = _get_steam_screenshots();
  if (iface) iface->HookScreenshots(hook);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamScreenshots::set_location
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamScreenshots::set_location(unsigned int h_screenshot, const std::string & location) {
  ISteamScreenshots *iface = _get_steam_screenshots();
  if (!iface) return false;
  return iface->SetLocation(h_screenshot, location.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamScreenshots::tag_user
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamScreenshots::tag_user(unsigned int h_screenshot, unsigned long long steam_id) {
  ISteamScreenshots *iface = _get_steam_screenshots();
  if (!iface) return false;
  return iface->TagUser(h_screenshot, CSteamID(steam_id));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamScreenshots::tag_published_file
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamScreenshots::tag_published_file(unsigned int h_screenshot, unsigned long long published_file_id) {
  ISteamScreenshots *iface = _get_steam_screenshots();
  if (!iface) return false;
  return iface->TagPublishedFile(h_screenshot, published_file_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamScreenshots::is_screenshots_hooked
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamScreenshots::is_screenshots_hooked() {
  ISteamScreenshots *iface = _get_steam_screenshots();
  if (!iface) return false;
  return iface->IsScreenshotsHooked();
}

#endif  // CPPPARSER
