// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamNetworking.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamNetworking interface pointer, or nullptr if not initialized.
static ISteamNetworking *_get_steam_networking() {
  return SteamAPI_SteamNetworking();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworking::accept_p2_p_session_with_user
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamNetworking::accept_p2_p_session_with_user(unsigned long long steam_id_remote) {
  ISteamNetworking *iface = _get_steam_networking();
  if (!iface) return false;
  return iface->AcceptP2PSessionWithUser(CSteamID(steam_id_remote));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworking::close_p2_p_session_with_user
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamNetworking::close_p2_p_session_with_user(unsigned long long steam_id_remote) {
  ISteamNetworking *iface = _get_steam_networking();
  if (!iface) return false;
  return iface->CloseP2PSessionWithUser(CSteamID(steam_id_remote));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworking::close_p2_p_channel_with_user
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamNetworking::close_p2_p_channel_with_user(unsigned long long steam_id_remote, int channel) {
  ISteamNetworking *iface = _get_steam_networking();
  if (!iface) return false;
  return iface->CloseP2PChannelWithUser(CSteamID(steam_id_remote), channel);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworking::allow_p2_p_packet_relay
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamNetworking::allow_p2_p_packet_relay(bool allow) {
  ISteamNetworking *iface = _get_steam_networking();
  if (!iface) return false;
  return iface->AllowP2PPacketRelay(allow);
}

#endif  // CPPPARSER
