// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamUserStats
// Description : Wrapper around ISteamUserStats.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamUserStats {
PUBLISHED:
  static bool set_stat(const std::string & name, int data);
  static bool set_stat(const std::string & name, float data);
  static bool update_avg_rate_stat(const std::string & name, float count_this_session, double d_session_length);
  static bool set_achievement(const std::string & name);
  static bool clear_achievement(const std::string & name);
  static bool store_stats();
  static int get_achievement_icon(const std::string & name);
  static std::string get_achievement_display_attribute(const std::string & name, const std::string & key);
  static bool indicate_achievement_progress(const std::string & name, unsigned int cur_progress, unsigned int max_progress);
  static unsigned int get_num_achievements();
  static std::string get_achievement_name(unsigned int achievement);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_user_stats(unsigned long long steam_id_user, PyObject *callback);
  static bool reset_all_stats(bool achievements_too);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long find_or_create_leaderboard(const std::string & leaderboard_name, int leaderboard_sort_method, int leaderboard_display_type, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long find_leaderboard(const std::string & leaderboard_name, PyObject *callback);
  static std::string get_leaderboard_name(unsigned long long h_steam_leaderboard);
  static int get_leaderboard_entry_count(unsigned long long h_steam_leaderboard);
  static int get_leaderboard_sort_method(unsigned long long h_steam_leaderboard);
  static int get_leaderboard_display_type(unsigned long long h_steam_leaderboard);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long download_leaderboard_entries(unsigned long long h_steam_leaderboard, int leaderboard_data_request, int range_start, int range_end, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long attach_leaderboard_ugc(unsigned long long h_steam_leaderboard, unsigned long long h_ugc, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_number_of_current_players(PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_global_achievement_percentages(PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_global_stats(int history_days, PyObject *callback);

private:
  SteamUserStats() = delete;
};
