// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamVideo
// Description : Wrapper around ISteamVideo.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamVideo {
PUBLISHED:
  static void get_video_url(unsigned int video_app_id);
  static void get_opf_settings(unsigned int video_app_id);

private:
  SteamVideo() = delete;
};
