// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamRemoteStorage.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamRemoteStorage interface pointer, or nullptr if not initialized.
static ISteamRemoteStorage *_get_steam_remote_storage() {
  return SteamAPI_SteamRemoteStorage();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::file_forget
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::file_forget(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->FileForget(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::file_delete
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::file_delete(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->FileDelete(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::set_sync_platforms
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::set_sync_platforms(const std::string & file, int remote_storage_platform) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->SetSyncPlatforms(file.c_str(), static_cast<ERemoteStoragePlatform>(remote_storage_platform));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::file_exists
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::file_exists(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->FileExists(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::file_persisted
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::file_persisted(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->FilePersisted(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::get_file_size
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamRemoteStorage::get_file_size(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return 0;
  return iface->GetFileSize(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::get_file_timestamp
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
long long SteamRemoteStorage::get_file_timestamp(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return 0;
  return iface->GetFileTimestamp(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::get_sync_platforms
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamRemoteStorage::get_sync_platforms(const std::string & file) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return 0;
  return iface->GetSyncPlatforms(file.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::get_file_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamRemoteStorage::get_file_count() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return 0;
  return iface->GetFileCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::is_cloud_enabled_for_account
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::is_cloud_enabled_for_account() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->IsCloudEnabledForAccount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::is_cloud_enabled_for_app
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::is_cloud_enabled_for_app() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->IsCloudEnabledForApp();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::set_cloud_enabled_for_app
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamRemoteStorage::set_cloud_enabled_for_app(bool enabled) {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (iface) iface->SetCloudEnabledForApp(enabled);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::get_cached_ugc_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamRemoteStorage::get_cached_ugc_count() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return 0;
  return iface->GetCachedUGCCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::get_local_file_change_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamRemoteStorage::get_local_file_change_count() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return 0;
  return iface->GetLocalFileChangeCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::begin_file_write_batch
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::begin_file_write_batch() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->BeginFileWriteBatch();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemoteStorage::end_file_write_batch
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemoteStorage::end_file_write_batch() {
  ISteamRemoteStorage *iface = _get_steam_remote_storage();
  if (!iface) return false;
  return iface->EndFileWriteBatch();
}

#endif  // CPPPARSER
