// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamUserStats.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamUserStats interface pointer, or nullptr if not initialized.
static ISteamUserStats *_get_steam_user_stats() {
  return SteamAPI_SteamUserStats();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::set_stat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::set_stat(const std::string & name, int data) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->SetStat(name.c_str(), data);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::set_stat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::set_stat(const std::string & name, float data) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->SetStat(name.c_str(), data);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::update_avg_rate_stat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::update_avg_rate_stat(const std::string & name, float count_this_session, double d_session_length) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->UpdateAvgRateStat(name.c_str(), count_this_session, d_session_length);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::set_achievement
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::set_achievement(const std::string & name) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->SetAchievement(name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::clear_achievement
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::clear_achievement(const std::string & name) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->ClearAchievement(name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::store_stats
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::store_stats() {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->StoreStats();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::get_achievement_icon
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamUserStats::get_achievement_icon(const std::string & name) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return 0;
  return iface->GetAchievementIcon(name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::get_achievement_display_attribute
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamUserStats::get_achievement_display_attribute(const std::string & name, const std::string & key) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return std::string();
  const char *result = iface->GetAchievementDisplayAttribute(name.c_str(), key.c_str());
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::indicate_achievement_progress
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::indicate_achievement_progress(const std::string & name, unsigned int cur_progress, unsigned int max_progress) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->IndicateAchievementProgress(name.c_str(), cur_progress, max_progress);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::get_num_achievements
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamUserStats::get_num_achievements() {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return 0;
  return iface->GetNumAchievements();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::get_achievement_name
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamUserStats::get_achievement_name(unsigned int achievement) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return std::string();
  const char *result = iface->GetAchievementName(achievement);
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUserStats::reset_all_stats
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUserStats::reset_all_stats(bool achievements_too) {
  ISteamUserStats *iface = _get_steam_user_stats();
  if (!iface) return false;
  return iface->ResetAllStats(achievements_too);
}

#endif  // CPPPARSER
