// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamUserStats
// Description : Wrapper around ISteamUserStats.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamUserStats {
PUBLISHED:
  static bool set_stat(const std::string & name, int data);
  static bool set_stat(const std::string & name, float data);
  static bool update_avg_rate_stat(const std::string & name, float count_this_session, double d_session_length);
  static bool set_achievement(const std::string & name);
  static bool clear_achievement(const std::string & name);
  static bool store_stats();
  static int get_achievement_icon(const std::string & name);
  static std::string get_achievement_display_attribute(const std::string & name, const std::string & key);
  static bool indicate_achievement_progress(const std::string & name, unsigned int cur_progress, unsigned int max_progress);
  static unsigned int get_num_achievements();
  static std::string get_achievement_name(unsigned int achievement);
  static bool reset_all_stats(bool achievements_too);

private:
  SteamUserStats() = delete;
};
