// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamMusic
// Description : Wrapper around ISteamMusic.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamMusic {
PUBLISHED:
  static bool is_enabled();
  static bool is_playing();
  static int get_playback_status();
  static void play();
  static void pause();
  static void play_previous();
  static void play_next();
  static void set_volume(float volume);
  static float get_volume();

private:
  SteamMusic() = delete;
};
