// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamNetworking.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamNetworking interface pointer, or nullptr if not initialized.
static ISteamNetworking *_get_steam_networking() {
  return SteamAPI_SteamNetworking();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworking::allow_p2_p_packet_relay
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamNetworking::allow_p2_p_packet_relay(bool allow) {
  ISteamNetworking *iface = _get_steam_networking();
  if (!iface) return false;
  return iface->AllowP2PPacketRelay(allow);
}

#endif  // CPPPARSER
