// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamGameServer.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamGameServer interface pointer, or nullptr if not initialized.
static ISteamGameServer *_get_steam_game_server() {
  return SteamAPI_SteamGameServer();
}

// Forward declarations for async call-result registration
extern void _steam_async_call_AssociateWithClanResult_t(SteamAPICall_t, PyObject *);
extern void _steam_async_call_ComputeNewPlayerCompatibilityResult_t(SteamAPICall_t, PyObject *);
extern void _steam_async_call_GSReputation_t(SteamAPICall_t, PyObject *);

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_product
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_product(const std::string & product) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetProduct(product.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_game_description
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_game_description(const std::string & game_description) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetGameDescription(game_description.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_mod_dir
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_mod_dir(const std::string & mod_dir) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetModDir(mod_dir.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_dedicated_server
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_dedicated_server(bool dedicated) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetDedicatedServer(dedicated);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::log_on
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::log_on(const std::string & token) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->LogOn(token.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::log_on_anonymous
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::log_on_anonymous() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->LogOnAnonymous();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::log_off
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::log_off() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->LogOff();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::logged_on
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServer::logged_on() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return false;
  return iface->BLoggedOn();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::secure
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServer::secure() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return false;
  return iface->BSecure();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::get_steam_id
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServer::get_steam_id() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return 0;
  return iface->GetSteamID().ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::was_restart_requested
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServer::was_restart_requested() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return false;
  return iface->WasRestartRequested();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_max_player_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_max_player_count(int players_max) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetMaxPlayerCount(players_max);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_bot_player_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_bot_player_count(int botplayers) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetBotPlayerCount(botplayers);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_server_name
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_server_name(const std::string & server_name) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetServerName(server_name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_map_name
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_map_name(const std::string & map_name) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetMapName(map_name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_password_protected
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_password_protected(bool password_protected) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetPasswordProtected(password_protected);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_spectator_port
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_spectator_port(unsigned short spectator_port) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetSpectatorPort(spectator_port);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_spectator_server_name
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_spectator_server_name(const std::string & spectator_server_name) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetSpectatorServerName(spectator_server_name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::clear_all_key_values
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::clear_all_key_values() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->ClearAllKeyValues();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_key_value
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_key_value(const std::string & key, const std::string & value) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetKeyValue(key.c_str(), value.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_game_tags
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_game_tags(const std::string & game_tags) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetGameTags(game_tags.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_game_data
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_game_data(const std::string & game_data) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetGameData(game_data.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_region
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_region(const std::string & region) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetRegion(region.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::set_advertise_server_active
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::set_advertise_server_active(bool active) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SetAdvertiseServerActive(active);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::end_auth_session
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::end_auth_session(unsigned long long steam_id) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->EndAuthSession(CSteamID(steam_id));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::cancel_auth_ticket
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::cancel_auth_ticket(unsigned int h_auth_ticket) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->CancelAuthTicket(h_auth_ticket);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::user_has_license_for_app
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamGameServer::user_has_license_for_app(unsigned long long steam_id, unsigned int app_id) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return 0;
  return iface->UserHasLicenseForApp(CSteamID(steam_id), app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::request_user_group_status
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServer::request_user_group_status(unsigned long long steam_id_user, unsigned long long steam_id_group) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return false;
  return iface->RequestUserGroupStatus(CSteamID(steam_id_user), CSteamID(steam_id_group));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::get_gameplay_stats
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::get_gameplay_stats() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->GetGameplayStats();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::get_server_reputation
//       Access: Published, Static
//  Description: Async. Invokes callback(dict) on completion.
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServer::get_server_reputation(PyObject *callback) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return 0;
  SteamAPICall_t call = iface->GetServerReputation();
  if (call == k_uAPICallInvalid) return 0;
  if (callback && callback != Py_None && PyCallable_Check(callback)) {
    _steam_async_call_GSReputation_t(call, callback);
  }
  return (unsigned long long)call;
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::associate_with_clan
//       Access: Published, Static
//  Description: Async. Invokes callback(dict) on completion.
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServer::associate_with_clan(unsigned long long steam_id_clan, PyObject *callback) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return 0;
  SteamAPICall_t call = iface->AssociateWithClan(CSteamID(steam_id_clan));
  if (call == k_uAPICallInvalid) return 0;
  if (callback && callback != Py_None && PyCallable_Check(callback)) {
    _steam_async_call_AssociateWithClanResult_t(call, callback);
  }
  return (unsigned long long)call;
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::compute_new_player_compatibility
//       Access: Published, Static
//  Description: Async. Invokes callback(dict) on completion.
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServer::compute_new_player_compatibility(unsigned long long steam_id_new_player, PyObject *callback) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return 0;
  SteamAPICall_t call = iface->ComputeNewPlayerCompatibility(CSteamID(steam_id_new_player));
  if (call == k_uAPICallInvalid) return 0;
  if (callback && callback != Py_None && PyCallable_Check(callback)) {
    _steam_async_call_ComputeNewPlayerCompatibilityResult_t(call, callback);
  }
  return (unsigned long long)call;
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::create_unauthenticated_user_connection
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServer::create_unauthenticated_user_connection() {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return 0;
  return iface->CreateUnauthenticatedUserConnection().ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::send_user_disconnect_deprecated
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamGameServer::send_user_disconnect_deprecated(unsigned long long steam_id_user) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (iface) iface->SendUserDisconnect_DEPRECATED(CSteamID(steam_id_user));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServer::update_user_data
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServer::update_user_data(unsigned long long steam_id_user, const std::string & player_name, unsigned int u_score) {
  ISteamGameServer *iface = _get_steam_game_server();
  if (!iface) return false;
  return iface->BUpdateUserData(CSteamID(steam_id_user), player_name.c_str(), u_score);
}

#endif  // CPPPARSER
