// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamUser.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamUser interface pointer, or nullptr if not initialized.
static ISteamUser *_get_steam_user() {
  return SteamAPI_SteamUser();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_h_steam_user
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamUser::get_h_steam_user() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return 0;
  return iface->GetHSteamUser();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::logged_on
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::logged_on() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BLoggedOn();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_steam_id
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned long long SteamUser::get_steam_id() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return 0;
  return iface->GetSteamID().ConvertToUint64();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::terminate_game_connection_deprecated
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamUser::terminate_game_connection_deprecated(unsigned int ip_server, unsigned short us_port_server) {
  ISteamUser *iface = _get_steam_user();
  if (iface) iface->TerminateGameConnection_DEPRECATED(ip_server, us_port_server);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_user_data_folder
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamUser::get_user_data_folder() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return std::string();
  char buf[1024];
  bool ok = iface->GetUserDataFolder(buf, sizeof(buf));
  if (ok) return std::string(buf);
  return std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::start_voice_recording
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamUser::start_voice_recording() {
  ISteamUser *iface = _get_steam_user();
  if (iface) iface->StartVoiceRecording();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::stop_voice_recording
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamUser::stop_voice_recording() {
  ISteamUser *iface = _get_steam_user();
  if (iface) iface->StopVoiceRecording();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_voice_optimal_sample_rate
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamUser::get_voice_optimal_sample_rate() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return 0;
  return iface->GetVoiceOptimalSampleRate();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_auth_ticket_for_web_api
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamUser::get_auth_ticket_for_web_api(const std::string & identity) {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return 0;
  return iface->GetAuthTicketForWebApi(identity.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::cancel_auth_ticket
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamUser::cancel_auth_ticket(unsigned int h_auth_ticket) {
  ISteamUser *iface = _get_steam_user();
  if (iface) iface->CancelAuthTicket(h_auth_ticket);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::is_behind_nat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::is_behind_nat() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BIsBehindNAT();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_game_badge_level
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamUser::get_game_badge_level(int series, bool foil) {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return 0;
  return iface->GetGameBadgeLevel(series, foil);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::get_player_steam_level
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamUser::get_player_steam_level() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return 0;
  return iface->GetPlayerSteamLevel();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::is_phone_verified
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::is_phone_verified() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BIsPhoneVerified();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::is_two_factor_enabled
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::is_two_factor_enabled() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BIsTwoFactorEnabled();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::is_phone_identifying
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::is_phone_identifying() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BIsPhoneIdentifying();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::is_phone_requiring_verification
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::is_phone_requiring_verification() {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BIsPhoneRequiringVerification();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUser::set_duration_control_online_state
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUser::set_duration_control_online_state(int new_state) {
  ISteamUser *iface = _get_steam_user();
  if (!iface) return false;
  return iface->BSetDurationControlOnlineState(static_cast<EDurationControlOnlineState>(new_state));
}

#endif  // CPPPARSER
