// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamUtils
// Description : Wrapper around ISteamUtils.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamUtils {
PUBLISHED:
  static unsigned int get_seconds_since_app_active();
  static unsigned int get_seconds_since_computer_active();
  static int get_connected_universe();
  static unsigned int get_server_real_time();
  static std::string get_ip_country();
  static unsigned char get_current_battery_power();
  static unsigned int get_app_id();
  static void set_overlay_notification_position(int notification_position);
  static unsigned int get_ipc_call_count();
  static bool is_overlay_enabled();
  static bool overlay_needs_present();
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long check_file_signature(const std::string & file_name, PyObject *callback);
  static bool show_gamepad_text_input(int input_mode, int line_input_mode, const std::string & description, unsigned int char_max, const std::string & existing_text);
  static unsigned int get_entered_gamepad_text_length();
  static std::string get_entered_gamepad_text_input();
  static std::string get_steam_ui_language();
  static bool is_steam_running_in_vr();
  static void set_overlay_notification_inset(int horizontal_inset, int vertical_inset);
  static bool is_steam_in_big_picture_mode();
  static void start_vr_dashboard();
  static bool is_vr_headset_streaming_enabled();
  static void set_vr_headset_streaming_enabled(bool enabled);
  static bool is_steam_china_launcher();
  static bool init_filter_text(unsigned int filter_options);
  static std::string filter_text(int context, unsigned long long source_steam_id, const std::string & input_message);
  static int get_i_pv6_connectivity_state(int protocol);
  static bool is_steam_running_on_steam_deck();
  static bool show_floating_gamepad_text_input(int keyboard_mode, int text_field_x_position, int text_field_y_position, int text_field_width, int text_field_height);
  static void set_game_launcher_mode(bool launcher_mode);
  static bool dismiss_floating_gamepad_text_input();
  static bool dismiss_gamepad_text_input();

private:
  SteamUtils() = delete;
};
