// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamGameServerStats
// Description : Wrapper around ISteamGameServerStats.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamGameServerStats {
PUBLISHED:
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_user_stats(unsigned long long steam_id_user, PyObject *callback);
  static bool set_user_stat(unsigned long long steam_id_user, const std::string & name, int data);
  static bool set_user_stat(unsigned long long steam_id_user, const std::string & name, float data);
  static bool update_user_avg_rate_stat(unsigned long long steam_id_user, const std::string & name, float count_this_session, double d_session_length);
  static bool set_user_achievement(unsigned long long steam_id_user, const std::string & name);
  static bool clear_user_achievement(unsigned long long steam_id_user, const std::string & name);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long store_user_stats(unsigned long long steam_id_user, PyObject *callback);

private:
  SteamGameServerStats() = delete;
};
