// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamRemotePlay.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamRemotePlay interface pointer, or nullptr if not initialized.
static ISteamRemotePlay *_get_steam_remote_play() {
  return SteamAPI_SteamRemotePlay();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemotePlay::get_session_count
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamRemotePlay::get_session_count() {
  ISteamRemotePlay *iface = _get_steam_remote_play();
  if (!iface) return 0;
  return iface->GetSessionCount();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemotePlay::show_remote_play_together_ui
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemotePlay::show_remote_play_together_ui() {
  ISteamRemotePlay *iface = _get_steam_remote_play();
  if (!iface) return false;
  return iface->ShowRemotePlayTogetherUI();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemotePlay::enable_remote_play_together_direct_input
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamRemotePlay::enable_remote_play_together_direct_input() {
  ISteamRemotePlay *iface = _get_steam_remote_play();
  if (!iface) return false;
  return iface->BEnableRemotePlayTogetherDirectInput();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamRemotePlay::disable_remote_play_together_direct_input
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamRemotePlay::disable_remote_play_together_direct_input() {
  ISteamRemotePlay *iface = _get_steam_remote_play();
  if (iface) iface->DisableRemotePlayTogetherDirectInput();
}

#endif  // CPPPARSER
