// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamMatchmaking
// Description : Wrapper around ISteamMatchmaking.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamMatchmaking {
PUBLISHED:
  static int get_favorite_game_count();
  static int add_favorite_game(unsigned int app_id, unsigned int ip, unsigned short conn_port, unsigned short query_port, unsigned int flags, unsigned int r_time32_last_played_on_server);
  static bool remove_favorite_game(unsigned int app_id, unsigned int ip, unsigned short conn_port, unsigned short query_port, unsigned int flags);
  static void add_request_lobby_list_string_filter(const std::string & key_to_match, const std::string & value_to_match, int comparison_type);
  static void add_request_lobby_list_numerical_filter(const std::string & key_to_match, int value_to_match, int comparison_type);
  static void add_request_lobby_list_near_value_filter(const std::string & key_to_match, int value_to_be_close_to);
  static void add_request_lobby_list_filter_slots_available(int slots_available);
  static void add_request_lobby_list_distance_filter(int lobby_distance_filter);
  static void add_request_lobby_list_result_count_filter(int max_results);
  static unsigned long long get_lobby_by_index(int lobby);

private:
  SteamMatchmaking() = delete;
};
