// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamFriends
// Description : Wrapper around ISteamFriends.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamFriends {
PUBLISHED:
  static std::string get_persona_name();
  static int get_persona_state();
  static int get_friend_count(int friend_flags);
  static unsigned long long get_friend_by_index(int friend_val, int friend_flags);
  static int get_friends_group_count();
  static int get_clan_count();
  static unsigned long long get_clan_by_index(int clan);
  static void activate_game_overlay(const std::string & dialog);
  static void activate_game_overlay_to_web_page(const std::string & url, int mode);
  static void activate_game_overlay_to_store(unsigned int app_id, int flag);
  static bool set_rich_presence(const std::string & key, const std::string & value);
  static void clear_rich_presence();
  static int get_coplay_friend_count();
  static unsigned long long get_coplay_friend(int coplay_friend);
  static bool set_listen_for_friends_messages(bool intercept_enabled);
  static int get_num_chats_with_unread_priority_messages();
  static bool register_protocol_in_overlay_browser(const std::string & protocol);
  static void activate_game_overlay_invite_dialog_connect_string(const std::string & connect_string);

private:
  SteamFriends() = delete;
};
