// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamApps
// Description : Static wrapper around the Steamworks ISteamApps
//               interface, providing access to app ownership,
//               DLC, language, and installation information.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamApps {
PUBLISHED:
  // Initialization - must be called before any other Steam methods.
  // Returns true if SteamAPI was initialized successfully.
  static bool init();
  static void shutdown();

  static bool is_subscribed();
  static bool is_low_violence();
  static bool is_cybercafe();
  static bool is_vac_banned();
  static std::string get_current_game_language();
  static std::string get_available_game_languages();
  static bool is_subscribed_app(unsigned int app_id);
  static bool is_dlc_installed(unsigned int app_id);
  static unsigned int get_earliest_purchase_unix_time(unsigned int app_id);
  static bool is_subscribed_from_free_weekend();
  static int get_dlc_count();
  static void install_dlc(unsigned int app_id);
  static void uninstall_dlc(unsigned int app_id);
  static void request_app_proof_of_purchase_key(unsigned int app_id);
  static std::string get_current_beta_name();
  static bool mark_content_corrupt(bool missing_files_only);
  static std::string get_app_install_dir(unsigned int app_id);
  static bool is_app_installed(unsigned int app_id);
  static unsigned long long get_app_owner();
  static std::string get_launch_query_param(const std::string & key);
  static int get_app_build_id();
  static void request_all_proof_of_purchase_keys();
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_file_details(const std::string & file_name, PyObject *callback);
  static std::string get_launch_command_line();
  static bool is_subscribed_from_family_sharing();
  static bool set_dlc_context(unsigned int app_id);
  static bool set_active_beta(const std::string & beta_name);

private:
  SteamApps() = delete;
};
