// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamParentalSettings.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamParentalSettings interface pointer, or nullptr if not initialized.
static ISteamParentalSettings *_get_steam_parental_settings() {
  return SteamAPI_SteamParentalSettings();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParentalSettings::is_parental_lock_enabled
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamParentalSettings::is_parental_lock_enabled() {
  ISteamParentalSettings *iface = _get_steam_parental_settings();
  if (!iface) return false;
  return iface->BIsParentalLockEnabled();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParentalSettings::is_parental_lock_locked
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamParentalSettings::is_parental_lock_locked() {
  ISteamParentalSettings *iface = _get_steam_parental_settings();
  if (!iface) return false;
  return iface->BIsParentalLockLocked();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParentalSettings::is_app_blocked
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamParentalSettings::is_app_blocked(unsigned int app_id) {
  ISteamParentalSettings *iface = _get_steam_parental_settings();
  if (!iface) return false;
  return iface->BIsAppBlocked(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParentalSettings::is_app_in_block_list
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamParentalSettings::is_app_in_block_list(unsigned int app_id) {
  ISteamParentalSettings *iface = _get_steam_parental_settings();
  if (!iface) return false;
  return iface->BIsAppInBlockList(app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParentalSettings::is_feature_blocked
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamParentalSettings::is_feature_blocked(int feature) {
  ISteamParentalSettings *iface = _get_steam_parental_settings();
  if (!iface) return false;
  return iface->BIsFeatureBlocked(static_cast<EParentalFeature>(feature));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParentalSettings::is_feature_in_block_list
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamParentalSettings::is_feature_in_block_list(int feature) {
  ISteamParentalSettings *iface = _get_steam_parental_settings();
  if (!iface) return false;
  return iface->BIsFeatureInBlockList(static_cast<EParentalFeature>(feature));
}

#endif  // CPPPARSER
