// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamMatchmakingServers
// Description : Wrapper around ISteamMatchmakingServers.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamMatchmakingServers {
PUBLISHED:
  static void cancel_server_query(int h_server_query);

private:
  SteamMatchmakingServers() = delete;
};
