// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamVideo.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamVideo interface pointer, or nullptr if not initialized.
static ISteamVideo *_get_steam_video() {
  return SteamAPI_SteamVideo();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamVideo::get_video_url
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamVideo::get_video_url(unsigned int video_app_id) {
  ISteamVideo *iface = _get_steam_video();
  if (iface) iface->GetVideoURL(video_app_id);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamVideo::get_opf_settings
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamVideo::get_opf_settings(unsigned int video_app_id) {
  ISteamVideo *iface = _get_steam_video();
  if (iface) iface->GetOPFSettings(video_app_id);
}

#endif  // CPPPARSER
