// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamInput.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamInput interface pointer, or nullptr if not initialized.
static ISteamInput *_get_steam_input() {
  return SteamAPI_SteamInput();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::init
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamInput::init(bool explicitly_call_run_frame) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return false;
  return iface->Init(explicitly_call_run_frame);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::shutdown
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamInput::shutdown() {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return false;
  return iface->Shutdown();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::set_input_action_manifest_file_path
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamInput::set_input_action_manifest_file_path(const std::string & input_action_manifest_absolute_path) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return false;
  return iface->SetInputActionManifestFilePath(input_action_manifest_absolute_path.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::run_frame
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamInput::run_frame(bool reserved_value) {
  ISteamInput *iface = _get_steam_input();
  if (iface) iface->RunFrame(reserved_value);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::wait_for_data
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamInput::wait_for_data(bool wait_forever, unsigned int timeout) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return false;
  return iface->BWaitForData(wait_forever, timeout);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::new_data_available
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamInput::new_data_available() {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return false;
  return iface->BNewDataAvailable();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::enable_device_callbacks
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamInput::enable_device_callbacks() {
  ISteamInput *iface = _get_steam_input();
  if (iface) iface->EnableDeviceCallbacks();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_glyph_png_for_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamInput::get_glyph_png_for_action_origin(int origin, int size, unsigned int flags) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return std::string();
  const char *result = iface->GetGlyphPNGForActionOrigin(static_cast<EInputActionOrigin>(origin), static_cast<ESteamInputGlyphSize>(size), flags);
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_glyph_svg_for_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamInput::get_glyph_svg_for_action_origin(int origin, unsigned int flags) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return std::string();
  const char *result = iface->GetGlyphSVGForActionOrigin(static_cast<EInputActionOrigin>(origin), flags);
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_glyph_for_action_origin_legacy
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamInput::get_glyph_for_action_origin_legacy(int origin) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return std::string();
  const char *result = iface->GetGlyphForActionOrigin_Legacy(static_cast<EInputActionOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_string_for_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamInput::get_string_for_action_origin(int origin) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return std::string();
  const char *result = iface->GetStringForActionOrigin(static_cast<EInputActionOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_string_for_xbox_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamInput::get_string_for_xbox_origin(int origin) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return std::string();
  const char *result = iface->GetStringForXboxOrigin(static_cast<EXboxOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_glyph_for_xbox_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
std::string SteamInput::get_glyph_for_xbox_origin(int origin) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return std::string();
  const char *result = iface->GetGlyphForXboxOrigin(static_cast<EXboxOrigin>(origin));
  return result ? std::string(result) : std::string();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::translate_action_origin
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamInput::translate_action_origin(int destination_input_type, int source_origin) {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return 0;
  return iface->TranslateActionOrigin(static_cast<ESteamInputType>(destination_input_type), static_cast<EInputActionOrigin>(source_origin));
}

////////////////////////////////////////////////////////////////////
//     Function: SteamInput::get_session_input_configuration_settings
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned short SteamInput::get_session_input_configuration_settings() {
  ISteamInput *iface = _get_steam_input();
  if (!iface) return 0;
  return iface->GetSessionInputConfigurationSettings();
}

#endif  // CPPPARSER
