// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamUGC
// Description : Wrapper around ISteamUGC.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamUGC {
PUBLISHED:
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long send_query_ugc_request(unsigned long long handle, PyObject *callback);
  static unsigned int get_query_ugc_num_tags(unsigned long long handle, unsigned int index);
  static std::string get_query_ugc_tag(unsigned long long handle, unsigned int index, unsigned int index_tag);
  static std::string get_query_ugc_tag_display_name(unsigned long long handle, unsigned int index, unsigned int index_tag);
  static std::string get_query_ugc_preview_url(unsigned long long handle, unsigned int index);
  static std::string get_query_ugc_metadata(unsigned long long handle, unsigned int index);
  static unsigned int get_query_ugc_num_additional_previews(unsigned long long handle, unsigned int index);
  static unsigned int get_query_ugc_num_key_value_tags(unsigned long long handle, unsigned int index);
  static std::string get_query_ugc_key_value_tag(unsigned long long handle, unsigned int index, unsigned int key_value_tag_index);
  static std::string get_query_ugc_key_value_tag(unsigned long long handle, unsigned int index, const std::string & key);
  static unsigned int get_num_supported_game_versions(unsigned long long handle, unsigned int index);
  static bool release_query_ugc_request(unsigned long long handle);
  static bool add_required_tag(unsigned long long handle, const std::string & tag_name);
  static bool add_excluded_tag(unsigned long long handle, const std::string & tag_name);
  static bool set_return_only_i_ds(unsigned long long handle, bool return_only_i_ds);
  static bool set_return_key_value_tags(unsigned long long handle, bool return_key_value_tags);
  static bool set_return_long_description(unsigned long long handle, bool return_long_description);
  static bool set_return_metadata(unsigned long long handle, bool return_metadata);
  static bool set_return_children(unsigned long long handle, bool return_children);
  static bool set_return_additional_previews(unsigned long long handle, bool return_additional_previews);
  static bool set_return_total_only(unsigned long long handle, bool return_total_only);
  static bool set_return_playtime_stats(unsigned long long handle, unsigned int days);
  static bool set_language(unsigned long long handle, const std::string & language);
  static bool set_allow_cached_response(unsigned long long handle, unsigned int max_age_seconds);
  static bool set_admin_query(unsigned long long handle, bool admin_query);
  static bool set_cloud_file_name_filter(unsigned long long handle, const std::string & match_cloud_file_name);
  static bool set_match_any_tag(unsigned long long handle, bool match_any_tag);
  static bool set_search_text(unsigned long long handle, const std::string & search_text);
  static bool set_ranked_by_trend_days(unsigned long long handle, unsigned int days);
  static bool set_time_created_date_range(unsigned long long handle, unsigned int rt_start, unsigned int rt_end);
  static bool set_time_updated_date_range(unsigned long long handle, unsigned int rt_start, unsigned int rt_end);
  static bool add_required_key_value_tag(unsigned long long handle, const std::string & key, const std::string & value);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_ugc_details(unsigned long long published_file_id, unsigned int max_age_seconds, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long create_item(unsigned int consumer_app_id, int file_type, PyObject *callback);
  static bool set_item_title(unsigned long long handle, const std::string & title);
  static bool set_item_description(unsigned long long handle, const std::string & description);
  static bool set_item_update_language(unsigned long long handle, const std::string & language);
  static bool set_item_metadata(unsigned long long handle, const std::string & meta_data);
  static bool set_item_visibility(unsigned long long handle, int visibility);
  static bool set_item_content(unsigned long long handle, const std::string & content_folder);
  static bool set_item_preview(unsigned long long handle, const std::string & preview_file);
  static bool set_allow_legacy_upload(unsigned long long handle, bool allow_legacy_upload);
  static bool remove_all_item_key_value_tags(unsigned long long handle);
  static bool remove_item_key_value_tags(unsigned long long handle, const std::string & key);
  static bool add_item_key_value_tag(unsigned long long handle, const std::string & key, const std::string & value);
  static bool add_item_preview_file(unsigned long long handle, const std::string & preview_file, int type);
  static bool add_item_preview_video(unsigned long long handle, const std::string & video_id);
  static bool update_item_preview_file(unsigned long long handle, unsigned int index, const std::string & preview_file);
  static bool update_item_preview_video(unsigned long long handle, unsigned int index, const std::string & video_id);
  static bool remove_item_preview(unsigned long long handle, unsigned int index);
  static bool add_content_descriptor(unsigned long long handle, int descid);
  static bool remove_content_descriptor(unsigned long long handle, int descid);
  static bool set_required_game_versions(unsigned long long handle, const std::string & game_branch_min, const std::string & game_branch_max);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long submit_item_update(unsigned long long handle, const std::string & change_note, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long set_user_item_vote(unsigned long long published_file_id, bool vote_up, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_user_item_vote(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long add_item_to_favorites(unsigned int app_id, unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long remove_item_from_favorites(unsigned int app_id, unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long subscribe_item(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long unsubscribe_item(unsigned long long published_file_id, PyObject *callback);
  static unsigned int get_num_subscribed_items(bool include_locally_disabled);
  static unsigned int get_item_state(unsigned long long published_file_id);
  static bool download_item(unsigned long long published_file_id, bool high_priority);
  static bool init_workshop_for_game_server(unsigned int workshop_depot_id, const std::string & folder);
  static void suspend_downloads(bool suspend);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long stop_playtime_tracking_for_all_items(PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long add_dependency(unsigned long long parent_published_file_id, unsigned long long child_published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long remove_dependency(unsigned long long parent_published_file_id, unsigned long long child_published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long add_app_dependency(unsigned long long published_file_id, unsigned int app_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long remove_app_dependency(unsigned long long published_file_id, unsigned int app_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_app_dependencies(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long delete_item(unsigned long long published_file_id, PyObject *callback);
  static bool show_workshop_eula();
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_workshop_eula_status(PyObject *callback);

private:
  SteamUGC() = delete;
};
