// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamMatchmakingServers.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamMatchmakingServers interface pointer, or nullptr if not initialized.
static ISteamMatchmakingServers *_get_steam_matchmaking_servers() {
  return SteamAPI_SteamMatchmakingServers();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMatchmakingServers::cancel_server_query
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamMatchmakingServers::cancel_server_query(int h_server_query) {
  ISteamMatchmakingServers *iface = _get_steam_matchmaking_servers();
  if (iface) iface->CancelServerQuery(h_server_query);
}

#endif  // CPPPARSER
