// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamNetworkingSockets.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamNetworkingSockets interface pointer, or nullptr if not initialized.
static ISteamNetworkingSockets *_get_steam_networking_sockets() {
  return SteamAPI_SteamNetworkingSockets_SteamAPI();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworkingSockets::init_authentication
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamNetworkingSockets::init_authentication() {
  ISteamNetworkingSockets *iface = _get_steam_networking_sockets();
  if (!iface) return 0;
  return iface->InitAuthentication();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworkingSockets::get_hosted_dedicated_server_port
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned short SteamNetworkingSockets::get_hosted_dedicated_server_port() {
  ISteamNetworkingSockets *iface = _get_steam_networking_sockets();
  if (!iface) return 0;
  return iface->GetHostedDedicatedServerPort();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworkingSockets::run_callbacks
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamNetworkingSockets::run_callbacks() {
  ISteamNetworkingSockets *iface = _get_steam_networking_sockets();
  if (iface) iface->RunCallbacks();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamNetworkingSockets::begin_async_request_fake_ip
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamNetworkingSockets::begin_async_request_fake_ip(int num_ports) {
  ISteamNetworkingSockets *iface = _get_steam_networking_sockets();
  if (!iface) return false;
  return iface->BeginAsyncRequestFakeIP(num_ports);
}

#endif  // CPPPARSER
