// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamParties.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamParties interface pointer, or nullptr if not initialized.
static ISteamParties *_get_steam_parties() {
  return SteamAPI_SteamParties();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamParties::get_num_active_beacons
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamParties::get_num_active_beacons() {
  ISteamParties *iface = _get_steam_parties();
  if (!iface) return 0;
  return iface->GetNumActiveBeacons();
}

#endif  // CPPPARSER
