// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamGameServer
// Description : Wrapper around ISteamGameServer.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamGameServer {
PUBLISHED:
  static void set_product(const std::string & product);
  static void set_game_description(const std::string & game_description);
  static void set_mod_dir(const std::string & mod_dir);
  static void set_dedicated_server(bool dedicated);
  static void log_on(const std::string & token);
  static void log_on_anonymous();
  static void log_off();
  static bool logged_on();
  static bool secure();
  static unsigned long long get_steam_id();
  static bool was_restart_requested();
  static void set_max_player_count(int players_max);
  static void set_bot_player_count(int botplayers);
  static void set_server_name(const std::string & server_name);
  static void set_map_name(const std::string & map_name);
  static void set_password_protected(bool password_protected);
  static void set_spectator_port(unsigned short spectator_port);
  static void set_spectator_server_name(const std::string & spectator_server_name);
  static void clear_all_key_values();
  static void set_key_value(const std::string & key, const std::string & value);
  static void set_game_tags(const std::string & game_tags);
  static void set_game_data(const std::string & game_data);
  static void set_region(const std::string & region);
  static void set_advertise_server_active(bool active);
  static void end_auth_session(unsigned long long steam_id);
  static void cancel_auth_ticket(unsigned int h_auth_ticket);
  static int user_has_license_for_app(unsigned long long steam_id, unsigned int app_id);
  static bool request_user_group_status(unsigned long long steam_id_user, unsigned long long steam_id_group);
  static void get_gameplay_stats();
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_server_reputation(PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long associate_with_clan(unsigned long long steam_id_clan, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long compute_new_player_compatibility(unsigned long long steam_id_new_player, PyObject *callback);
  static unsigned long long create_unauthenticated_user_connection();
  static void send_user_disconnect_deprecated(unsigned long long steam_id_user);
  static bool update_user_data(unsigned long long steam_id_user, const std::string & player_name, unsigned int u_score);

private:
  SteamGameServer() = delete;
};
