// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamGameServerStats.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamGameServerStats interface pointer, or nullptr if not initialized.
static ISteamGameServerStats *_get_steam_game_server_stats() {
  return SteamAPI_SteamGameServerStats();
}

// Forward declarations for async call-result registration
extern void _steam_async_call_GSStatsReceived_t(SteamAPICall_t, PyObject *);
extern void _steam_async_call_GSStatsStored_t(SteamAPICall_t, PyObject *);

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::request_user_stats
//       Access: Published, Static
//  Description: Async. Invokes callback(dict) on completion.
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServerStats::request_user_stats(unsigned long long steam_id_user, PyObject *callback) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return 0;
  SteamAPICall_t call = iface->RequestUserStats(CSteamID(steam_id_user));
  if (call == k_uAPICallInvalid) return 0;
  if (callback && callback != Py_None && PyCallable_Check(callback)) {
    _steam_async_call_GSStatsReceived_t(call, callback);
  }
  return (unsigned long long)call;
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::set_user_stat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServerStats::set_user_stat(unsigned long long steam_id_user, const std::string & name, int data) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return false;
  return iface->SetUserStat(CSteamID(steam_id_user), name.c_str(), data);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::set_user_stat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServerStats::set_user_stat(unsigned long long steam_id_user, const std::string & name, float data) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return false;
  return iface->SetUserStat(CSteamID(steam_id_user), name.c_str(), data);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::update_user_avg_rate_stat
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServerStats::update_user_avg_rate_stat(unsigned long long steam_id_user, const std::string & name, float count_this_session, double d_session_length) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return false;
  return iface->UpdateUserAvgRateStat(CSteamID(steam_id_user), name.c_str(), count_this_session, d_session_length);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::set_user_achievement
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServerStats::set_user_achievement(unsigned long long steam_id_user, const std::string & name) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return false;
  return iface->SetUserAchievement(CSteamID(steam_id_user), name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::clear_user_achievement
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamGameServerStats::clear_user_achievement(unsigned long long steam_id_user, const std::string & name) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return false;
  return iface->ClearUserAchievement(CSteamID(steam_id_user), name.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamGameServerStats::store_user_stats
//       Access: Published, Static
//  Description: Async. Invokes callback(dict) on completion.
////////////////////////////////////////////////////////////////////
unsigned long long SteamGameServerStats::store_user_stats(unsigned long long steam_id_user, PyObject *callback) {
  ISteamGameServerStats *iface = _get_steam_game_server_stats();
  if (!iface) return 0;
  SteamAPICall_t call = iface->StoreUserStats(CSteamID(steam_id_user));
  if (call == k_uAPICallInvalid) return 0;
  if (callback && callback != Py_None && PyCallable_Check(callback)) {
    _steam_async_call_GSStatsStored_t(call, callback);
  }
  return (unsigned long long)call;
}

#endif  // CPPPARSER
