// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamRemoteStorage
// Description : Wrapper around ISteamRemoteStorage.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamRemoteStorage {
PUBLISHED:
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long file_read_async(const std::string & file, unsigned int offset, unsigned int to_read, PyObject *callback);
  static bool file_forget(const std::string & file);
  static bool file_delete(const std::string & file);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long file_share(const std::string & file, PyObject *callback);
  static bool set_sync_platforms(const std::string & file, int remote_storage_platform);
  static bool file_exists(const std::string & file);
  static bool file_persisted(const std::string & file);
  static int get_file_size(const std::string & file);
  static long long get_file_timestamp(const std::string & file);
  static int get_sync_platforms(const std::string & file);
  static int get_file_count();
  static bool is_cloud_enabled_for_account();
  static bool is_cloud_enabled_for_app();
  static void set_cloud_enabled_for_app(bool enabled);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long ugc_download(unsigned long long h_content, unsigned int priority, PyObject *callback);
  static int get_cached_ugc_count();
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_published_file_details(unsigned long long published_file_id, unsigned int max_seconds_old, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long delete_published_file(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long enumerate_user_published_files(unsigned int start_index, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long subscribe_published_file(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long enumerate_user_subscribed_files(unsigned int start_index, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long unsubscribe_published_file(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_published_item_vote_details(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long update_user_published_item_vote(unsigned long long published_file_id, bool vote_up, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long get_user_published_item_vote_details(unsigned long long published_file_id, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long set_user_published_file_action(unsigned long long published_file_id, int action, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long enumerate_published_files_by_user_action(int action, unsigned int start_index, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long ugc_download_to_location(unsigned long long h_content, const std::string & location, unsigned int priority, PyObject *callback);
  static int get_local_file_change_count();
  static bool begin_file_write_batch();
  static bool end_file_write_batch();

  // Write a string to a file in Steam Cloud.
  static bool file_write(const std::string &file, const std::string &data);

  // Read the contents of a Steam Cloud file as a string.
  static std::string file_read(const std::string &file);

private:
  SteamRemoteStorage() = delete;
};
