// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamHTMLSurface.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamHTMLSurface interface pointer, or nullptr if not initialized.
static ISteamHTMLSurface *_get_steam_html_surface() {
  return SteamAPI_SteamHTMLSurface();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamHTMLSurface::init
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamHTMLSurface::init() {
  ISteamHTMLSurface *iface = _get_steam_html_surface();
  if (!iface) return false;
  return iface->Init();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamHTMLSurface::shutdown
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamHTMLSurface::shutdown() {
  ISteamHTMLSurface *iface = _get_steam_html_surface();
  if (!iface) return false;
  return iface->Shutdown();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamHTMLSurface::set_cookie
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamHTMLSurface::set_cookie(const std::string & hostname, const std::string & key, const std::string & value, const std::string & path, unsigned int expires, bool secure, bool http_only) {
  ISteamHTMLSurface *iface = _get_steam_html_surface();
  if (iface) iface->SetCookie(hostname.c_str(), key.c_str(), value.c_str(), path.c_str(), expires, secure, http_only);
}

#endif  // CPPPARSER
