// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include "steamPython.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamMatchmaking
// Description : Wrapper around ISteamMatchmaking.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamMatchmaking {
PUBLISHED:
  static int get_favorite_game_count();
  static int add_favorite_game(unsigned int app_id, unsigned int ip, unsigned short conn_port, unsigned short query_port, unsigned int flags, unsigned int r_time32_last_played_on_server);
  static bool remove_favorite_game(unsigned int app_id, unsigned int ip, unsigned short conn_port, unsigned short query_port, unsigned int flags);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long request_lobby_list(PyObject *callback);
  static void add_request_lobby_list_string_filter(const std::string & key_to_match, const std::string & value_to_match, int comparison_type);
  static void add_request_lobby_list_numerical_filter(const std::string & key_to_match, int value_to_match, int comparison_type);
  static void add_request_lobby_list_near_value_filter(const std::string & key_to_match, int value_to_be_close_to);
  static void add_request_lobby_list_filter_slots_available(int slots_available);
  static void add_request_lobby_list_distance_filter(int lobby_distance_filter);
  static void add_request_lobby_list_result_count_filter(int max_results);
  static void add_request_lobby_list_compatible_members_filter(unsigned long long steam_id_lobby);
  static unsigned long long get_lobby_by_index(int lobby);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long create_lobby(int lobby_type, int max_members, PyObject *callback);
  // Async: callback receives dict with result fields.
  // Returns call handle (0 on failure).
  static unsigned long long join_lobby(unsigned long long steam_id_lobby, PyObject *callback);
  static void leave_lobby(unsigned long long steam_id_lobby);
  static bool invite_user_to_lobby(unsigned long long steam_id_lobby, unsigned long long steam_id_invitee);
  static int get_num_lobby_members(unsigned long long steam_id_lobby);
  static unsigned long long get_lobby_member_by_index(unsigned long long steam_id_lobby, int member);
  static std::string get_lobby_data(unsigned long long steam_id_lobby, const std::string & key);
  static bool set_lobby_data(unsigned long long steam_id_lobby, const std::string & key, const std::string & value);
  static int get_lobby_data_count(unsigned long long steam_id_lobby);
  static std::string get_lobby_data_by_index(unsigned long long steam_id_lobby, int lobby_data);
  static bool delete_lobby_data(unsigned long long steam_id_lobby, const std::string & key);
  static std::string get_lobby_member_data(unsigned long long steam_id_lobby, unsigned long long steam_id_user, const std::string & key);
  static void set_lobby_member_data(unsigned long long steam_id_lobby, const std::string & key, const std::string & value);
  static bool request_lobby_data(unsigned long long steam_id_lobby);
  static void set_lobby_game_server(unsigned long long steam_id_lobby, unsigned int game_server_ip, unsigned short game_server_port, unsigned long long steam_id_game_server);
  static bool set_lobby_member_limit(unsigned long long steam_id_lobby, int max_members);
  static int get_lobby_member_limit(unsigned long long steam_id_lobby);
  static bool set_lobby_type(unsigned long long steam_id_lobby, int lobby_type);
  static bool set_lobby_joinable(unsigned long long steam_id_lobby, bool lobby_joinable);
  static unsigned long long get_lobby_owner(unsigned long long steam_id_lobby);
  static bool set_lobby_owner(unsigned long long steam_id_lobby, unsigned long long steam_id_new_owner);
  static bool set_linked_lobby(unsigned long long steam_id_lobby, unsigned long long steam_id_lobby_dependent);

private:
  SteamMatchmaking() = delete;
};
