// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamUGC
// Description : Wrapper around ISteamUGC.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamUGC {
PUBLISHED:
  static unsigned int get_num_subscribed_items(bool include_locally_disabled);
  static bool init_workshop_for_game_server(unsigned int workshop_depot_id, const std::string & folder);
  static void suspend_downloads(bool suspend);
  static bool show_workshop_eula();

private:
  SteamUGC() = delete;
};
