// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamUGC.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamUGC interface pointer, or nullptr if not initialized.
static ISteamUGC *_get_steam_ugc() {
  return SteamAPI_SteamUGC();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUGC::get_num_subscribed_items
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
unsigned int SteamUGC::get_num_subscribed_items(bool include_locally_disabled) {
  ISteamUGC *iface = _get_steam_ugc();
  if (!iface) return 0;
  return iface->GetNumSubscribedItems(include_locally_disabled);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUGC::init_workshop_for_game_server
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUGC::init_workshop_for_game_server(unsigned int workshop_depot_id, const std::string & folder) {
  ISteamUGC *iface = _get_steam_ugc();
  if (!iface) return false;
  return iface->BInitWorkshopForGameServer(workshop_depot_id, folder.c_str());
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUGC::suspend_downloads
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamUGC::suspend_downloads(bool suspend) {
  ISteamUGC *iface = _get_steam_ugc();
  if (iface) iface->SuspendDownloads(suspend);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamUGC::show_workshop_eula
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamUGC::show_workshop_eula() {
  ISteamUGC *iface = _get_steam_ugc();
  if (!iface) return false;
  return iface->ShowWorkshopEULA();
}

#endif  // CPPPARSER
