// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#include "steamMusic.h"

// Guard everything below from interrogate's parser.
#ifndef CPPPARSER

#include <steam/steam_api.h>
#include <steam/steam_api_flat.h>

// Helper: returns the ISteamMusic interface pointer, or nullptr if not initialized.
static ISteamMusic *_get_steam_music() {
  return SteamAPI_SteamMusic();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::is_enabled
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamMusic::is_enabled() {
  ISteamMusic *iface = _get_steam_music();
  if (!iface) return false;
  return iface->BIsEnabled();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::is_playing
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
bool SteamMusic::is_playing() {
  ISteamMusic *iface = _get_steam_music();
  if (!iface) return false;
  return iface->BIsPlaying();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::get_playback_status
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
int SteamMusic::get_playback_status() {
  ISteamMusic *iface = _get_steam_music();
  if (!iface) return 0;
  return iface->GetPlaybackStatus();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::play
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamMusic::play() {
  ISteamMusic *iface = _get_steam_music();
  if (iface) iface->Play();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::pause
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamMusic::pause() {
  ISteamMusic *iface = _get_steam_music();
  if (iface) iface->Pause();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::play_previous
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamMusic::play_previous() {
  ISteamMusic *iface = _get_steam_music();
  if (iface) iface->PlayPrevious();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::play_next
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamMusic::play_next() {
  ISteamMusic *iface = _get_steam_music();
  if (iface) iface->PlayNext();
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::set_volume
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
void SteamMusic::set_volume(float volume) {
  ISteamMusic *iface = _get_steam_music();
  if (iface) iface->SetVolume(volume);
}

////////////////////////////////////////////////////////////////////
//     Function: SteamMusic::get_volume
//       Access: Published, Static
////////////////////////////////////////////////////////////////////
float SteamMusic::get_volume() {
  ISteamMusic *iface = _get_steam_music();
  if (!iface) return 0.0f;
  return iface->GetVolume();
}

#endif  // CPPPARSER
