// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"

////////////////////////////////////////////////////////////////////
//       Class : SteamParentalSettings
// Description : Wrapper around ISteamParentalSettings.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamParentalSettings {
PUBLISHED:
  static bool is_parental_lock_enabled();
  static bool is_parental_lock_locked();
  static bool is_app_blocked(unsigned int app_id);
  static bool is_app_in_block_list(unsigned int app_id);
  static bool is_feature_blocked(int feature);
  static bool is_feature_in_block_list(int feature);

private:
  SteamParentalSettings() = delete;
};
