// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamNetworkingUtils
// Description : Wrapper around ISteamNetworkingUtils.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamNetworkingUtils {
PUBLISHED:
  static void init_relay_network_access();
  static bool check_ping_data_up_to_date(float max_age_seconds);
  static int get_pop_count();
  static bool is_fake_i_pv4(unsigned int i_pv4);
  static int get_i_pv4_fake_ip_type(unsigned int i_pv4);
  static bool set_global_config_value_int32(int value, int val);
  static bool set_global_config_value_float(int value, float val);
  static bool set_global_config_value_string(int value, const std::string & val);
  static int iterate_generic_editable_config_values(int current, bool enumerate_dev_vars);

private:
  SteamNetworkingUtils() = delete;
};
