// ======================================================================
// AUTO-GENERATED by scripts/codegen.py - DO NOT EDIT BY HAND.
// Re-generate with:  ppython scripts/codegen.py
// ======================================================================

#pragma once

#include "pandabase.h"
#include <string>

////////////////////////////////////////////////////////////////////
//       Class : SteamUser
// Description : Wrapper around ISteamUser.
////////////////////////////////////////////////////////////////////
class EXPORT_CLASS SteamUser {
PUBLISHED:
  static int get_h_steam_user();
  static bool logged_on();
  static unsigned long long get_steam_id();
  static void terminate_game_connection_deprecated(unsigned int ip_server, unsigned short us_port_server);
  static std::string get_user_data_folder();
  static void start_voice_recording();
  static void stop_voice_recording();
  static unsigned int get_voice_optimal_sample_rate();
  static unsigned int get_auth_ticket_for_web_api(const std::string & identity);
  static void cancel_auth_ticket(unsigned int h_auth_ticket);
  static bool is_behind_nat();
  static int get_game_badge_level(int series, bool foil);
  static int get_player_steam_level();
  static bool is_phone_verified();
  static bool is_two_factor_enabled();
  static bool is_phone_identifying();
  static bool is_phone_requiring_verification();
  static bool set_duration_control_online_state(int new_state);

private:
  SteamUser() = delete;
};
